"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

import os
from pathlib import Path

# ============================================================
# 1. БАЗОВЫЕ НАСТРОЙКИ
# ============================================================

# Корневая директория проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Секретный ключ (для разработки, в продакшене заменить!)
SECRET_KEY = 'django-insecure-your-secret-key-here-change-in-production'

# Режим отладки (включён только для разработки)
DEBUG = True

# Разрешённые хосты ('*' означает "любой" - только для разработки!)
ALLOWED_HOSTS = ['*']


# ============================================================
# 2. УСТАНОВЛЕННЫЕ ПРИЛОЖЕНИЯ
# ============================================================

INSTALLED_APPS = [
    # Стандартные приложения Django
    'django.contrib.admin',        # Административная панель
    'django.contrib.auth',         # Аутентификация (пользователи)
    'django.contrib.contenttypes', # Работа с типами контента
    'django.contrib.sessions',     # Сессии пользователей
    'django.contrib.messages',     # Системные сообщения (flash-сообщения)
    'django.contrib.staticfiles',  # Статические файлы (CSS, JS)
    
    # ===== СТОРОННИЕ ПРИЛОЖЕНИЯ =====
    'rest_framework',      # Для создания REST API (React будет получать данные)
    'corsheaders',         # Разрешает запросы с React (разные порты: 3000 и 8000)
    'django_filters',      # Для фильтрации фото по категориям
    
    # ===== НАШЕ ПРИЛОЖЕНИЕ =====
    'photos',              # Приложение для фотоальбома
]


# ============================================================
# 3. ПРОМЕЖУТОЧНЫЕ СЛОИ (MIDDLEWARE)
# ============================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← ДОЛЖЕН БЫТЬ ПЕРВЫМ!
    # ВАЖНО: CorsMiddleware должен быть самым первым в списке,
    # чтобы обрабатывать CORS-заголовки до остальных middleware
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# 4. МАРШРУТИЗАЦИЯ URL
# ============================================================

# Файл с корневыми URL-адресами
ROOT_URLCONF = 'backend.urls'


# ============================================================
# 5. ШАБЛОНЫ (TEMPLATES)
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Пути к папкам с шаблонами (пока пусто)
        'APP_DIRS': True,  # Искать шаблоны в папках templates каждого приложения
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# 6. WSGI (Web Server Gateway Interface)
# ============================================================

# Точка входа для серверов (например, для Gunicorn)
WSGI_APPLICATION = 'backend.wsgi.application'


# ============================================================
# 7. БАЗА ДАННЫХ (POSTGRESQL)
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Используем PostgreSQL
        'NAME': 'photo_albom',                      # Имя базы данных
        'USER': 'myuser',                          # Пользователь базы данных
        'PASSWORD': 'mypassword',                  # Пароль пользователя
        'HOST': 'localhost',                       # Хост (Docker контейнер)
        'PORT': '5432',                           # Порт PostgreSQL (стандартный)
    }
}


# ============================================================
# 8. ВАЛИДАЦИЯ ПАРОЛЕЙ
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================
# 9. ИНТЕРНАЦИОНАЛИЗАЦИЯ (ЯЗЫК И ВРЕМЯ)
# ============================================================

# Язык интерфейса
LANGUAGE_CODE = 'ru-ru'          # ← Русский язык

# Часовой пояс
TIME_ZONE = 'Europe/Moscow'      # ← Московское время

# Включить интернационализацию
USE_I18N = True

# Использовать временные зоны
USE_TZ = True


# ============================================================
# 10. СТАТИЧЕСКИЕ И МЕДИА-ФАЙЛЫ
# ============================================================

# URL для статических файлов (CSS, JS, изображения)
STATIC_URL = 'static/'

# Папка для сбора статических файлов (для продакшена)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# URL для медиа-файлов (пользовательские загрузки)
MEDIA_URL = '/media/'

# Папка для медиа-файлов (загруженные изображения)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ============================================================
# 11. ПЕРВИЧНЫЙ КЛЮЧ ПО УМОЛЧАНИЮ
# ============================================================

# Тип поля для первичного ключа по умолчанию
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# 12. НАСТРОЙКИ ДЛЯ CORS (Cross-Origin Resource Sharing)
# ============================================================

# Разрешаем React-приложению (на порту 3000) обращаться к API (на порту 8000)
CORS_ALLOW_ALL_ORIGINS = True      # Разрешить запросы с любых доменов (только для разработки!)
CORS_ALLOW_CREDENTIALS = True      # Разрешить отправку куки и заголовков авторизации


# ============================================================
# 13. НАСТРОЙКИ ДЛЯ DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {
    # Фильтры для API
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # Фильтрация по полям
        'rest_framework.filters.SearchFilter',               # Поиск по тексту
        'rest_framework.filters.OrderingFilter',             # Сортировка
    ],
    
    # Пагинация (разбивка на страницы)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,  # 20 записей на странице
    
    # Формат ответа
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',        # JSON для React
        'rest_framework.renderers.BrowsableAPIRenderer', # Красивый интерфейс в браузере
    ]
}